# **Handling Misssing Values**

In [19]:
from pandas import read_csv as rc
import pandas as pd
#from sklearn.liner

In [20]:
df=rc('/Users/rayquaza/Desktop/mlops/workshop/ICE-Workshop/datasets/linear regression/homeprices_multivariable_linear_regression.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

## **to handle the missing value**<br><br>
--> **method 1**- drop the column
use:dropna(inplace=True)<br><br><br>
--> **method 2**- fill the missing value with mean/median/mode<br>
mean-takes the mean<br>
mode-takes the msot repeted element<br>
median-middle elemnt<br>
use:.fillna()

In [21]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [27]:
#x=df.dropna(inplace=True)

In [28]:
import math
median=math.ceil(df.bedrooms.median())
median

4

In [29]:
df.bedrooms.fillna(median,inplace=True)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000