# **Deep Learning**

--> **ANN**<br>
--> **CNN**<br>
--> **RNN**<br>
--> **GNN**<br>

## **Heart Disease Prediction**

In [35]:
#import libraries
import pandas as pd
from pandas import read_csv as rc
from sklearn.tree import DecisionTreeClassifier

In [36]:
#Load the dataset
df=rc('/Users/rayquaza/Desktop/mlops/workshop/ICE-Workshop/datasets/heart.csv')
df

      age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca  thal  target
0      52    1   0       125   212  ...      1.0      2   2     3       0
1      53    1   0       140   203  ...      3.1      0   0     3       0
2      70    1   0       145   174  ...      2.6      0   0     3       0
3      61    1   0       148   203  ...      0.0      2   1     3       0
4      62    0   0       138   294  ...      1.9      1   3     2       0
...   ...  ...  ..       ...   ...  ...      ...    ...  ..   ...     ...
1020   59    1   1       140   221  ...      0.0      2   0     2       1
1021   60    1   0       125   258  ...      2.8      1   1     3       0
1022   47    1   0       110   275  ...      1.0      1   1     2       0
1023   50    0   0       110   254  ...      0.0      2   0     2       1
1024   54    1   0       120   188  ...      1.4      1   1     3       0

[1025 rows x 14 columns]

In [37]:
#Data statistics
df.shape

(1025, 14)

In [38]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [39]:
df.describe()

               age          sex  ...         thal       target
count  1025.000000  1025.000000  ...  1025.000000  1025.000000
mean     54.434146     0.695610  ...     2.323902     0.513171
std       9.072290     0.460373  ...     0.620660     0.500070
min      29.000000     0.000000  ...     0.000000     0.000000
25%      48.000000     0.000000  ...     2.000000     0.000000
50%      56.000000     1.000000  ...     2.000000     1.000000
75%      61.000000     1.000000  ...     3.000000     1.000000
max      77.000000     1.000000  ...     3.000000     1.000000

[8 rows x 14 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [41]:
#Split the dataset into x and y
x=df.drop('target',axis=1)
y=df['target']

In [42]:
x

      age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0      52    1   0       125   212  ...      0      1.0      2   2     3
1      53    1   0       140   203  ...      1      3.1      0   0     3
2      70    1   0       145   174  ...      1      2.6      0   0     3
3      61    1   0       148   203  ...      0      0.0      2   1     3
4      62    0   0       138   294  ...      0      1.9      1   3     2
...   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
1020   59    1   1       140   221  ...      1      0.0      2   0     2
1021   60    1   0       125   258  ...      1      2.8      1   1     3
1022   47    1   0       110   275  ...      1      1.0      1   1     2
1023   50    0   0       110   254  ...      0      0.0      2   0     2
1024   54    1   0       120   188  ...      0      1.4      1   1     3

[1025 rows x 13 columns]

In [43]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [44]:
#train test split
from sklearn.model_selection import train_test_split as tts

In [45]:
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.2,random_state=42) #you can give test_size=0.8
#random_state tends to go for best fit line

In [46]:
x_train.shape

(820, 13)

In [47]:
x_test.shape

(205, 13)

In [48]:
#call the model and train the model
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [49]:
#make predictions usinfg usrer input
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [50]:
pred=dt.predict([[53,1,0,140,203,1,0,155,1,3.1,0,0,3]])
pred

/opt/anaconda3/envs/tf2.18/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [51]:
if pred.item() is 0:
    print('will not die')
else:
    print('will die')

will not die

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
/var/folders/wd/28dthdw16pg5_wrd6f76dg4h0000gn/T/ipykernel_2759/16385984.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if pred.item() is 0:

In [53]:
#model evaluation
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [59]:
y_pred=dt.predict(x_test)
acc=accuracy_score(y_test,y_pred)

In [61]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.97      0.99       103

    accuracy                           0.99       205
   macro avg       0.99      0.99      0.99       205
weighted avg       0.99      0.99      0.99       205

In [63]:
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

[[102   0]
 [  3 100]]

This is how you read confusion matrix<br>
[True-negative,False-Posative]<br>
[False-neagtive,True-Posative]